---
- name: Upload New Certificate to FortiWeb
  hosts: fortiweb
  gather_facts: false
  collections:
    - fortinet.fortiweb
  vars:
    #sys_id: '1bc7749b47627590d2bbe228436d4378'

  tasks:

  - name: Set certificate fact
    ansible.builtin.set_fact:
      certificate: "/tmp/{{ fwebos_certificate }}.p12"

  - name: Download file and force basic auth
    ansible.builtin.get_url:
      url: "{{ SN_HOST }}/api/now/attachment/{{ sys_id }}/file"
      dest: "{{ certificate }}"
      force_basic_auth: yes
      username: "{{ SN_USERNAME }}"
      password: "{{ SN_PASSWORD }}"
    delegate_to: localhost

  - name: Upload pkcs12 certificate 
    # this tasks expects that a previous task or template 
    # was run to get the certificate from ServiceNow, and
    # that the p12 certificate was placed in /tmp/cert.p12
    fwebos_certificate_local_import_certificate:
      action: add
      vdom: root
      type: PKCS12Certificate
      certificateWithKeyFile: "{{ certificate }}"
      password: PASSW0RD
    no_log: true
