---
- name: Configure Variables for Workflow
  hosts: localhost
  gather_facts: false
  become: false
  tasks:

  - name: Create Virtual IP variable
    ansible.builtin.set_fact:
      fwebos_virtual_server_name: "{{ fwebos_virtual_server | replace('.','_') }}"   

  - name: Set variables for workflow
    ansible.builtin.set_stats:
      data:
        fwebos_virtual_server_name: "{{ fwebos_virtual_server_name }}"
        fwebos_server_pool: "{{ fwebos_virtual_server_name }}_pool"
        fwebos_server_policy: "{{ fwebos_virtual_server }}_policy"
        fwebos_vip_name: "{{ fwebos_virtual_server_name }}_vip"   
        fwebos_certificate: "{{ fwebos_virtual_server_name }}_{{ sys_id }}"
