---
- name: Configure virtual server name
  hosts: fortiweb
  gather_facts: false
  collections:
    - fortinet.fortiweb
  vars:

  tasks:

  - name: Create a Virtual Server
    fwebos_virtual_server:
      action: add
      name: "{{  fwebos_virtual_server_name }}"
      #name: "{{ item.name }}"
      vdom: root
    ignore_errors: true
    #loop: "{{ fwebos_virtual_servers }}"
    register: create_vs_result

  - name: Debug output of Create a Virtual Server
    ansible.builtin.debug:
      msg: "{{ create_vs_result }}"
      verbosity: 3

  - name: fail the play if the previous command did not succeed
    ansible.builtin.fail:
      msg: "{{ create_vs_result.res.results.message }}"
    when:
      - create_vs_result.failed == true
      - create_vs_result.res.results.message != 'A duplicate entry has already existed.'