---
- name: Configure virtual server vip
  hosts: fortiweb
  gather_facts: false
  collections:
    - fortinet.fortiweb
  # variables defined in fwebos_server_variables.yml

  tasks:
  - name: Create Virtual Server VIP
    fwebos_virtual_server_vip:
      action: add
      table_name: "{{ fwebos_virtual_server_name }}"
      vip: "{{ fwebos_vip_name }}"
      status: enable
      vdom: root
    ignore_errors: true
    register: virtual_server_vip_result

  - name: Debug Create Virtual Server VIP result 
    ansible.builtin.debug:
      msg: "{{ virtual_server_vip_result }}"
      verbosity: 3

  - name: fail the play if the previous command did not succeed
    ansible.builtin.fail:
      msg: "{{ virtual_server_vip_result.res.results.message }}"
    when:
      - virtual_server_vip_result.failed == true
      - virtual_server_vip_result.res.results.message != 'A duplicate entry has already existed.'
