---
- name: Create Server Pool
  hosts: fortiweb
  gather_facts: false
  collections:
  - fortinet.fortiweb
  # variables defined in fwebos_server_variables.yml

  tasks:
  - name: Create Server Pool 
    fwebos_server_pool:
      action: add 
      vdom: root
      name: "{{ fwebos_server_pool }}"
      type: reverse-proxy
      server_balance: disable
      #server_balance: enable
      lb_algo: round-robin
      # health: HLTHCK_ICMP
      # persistence: test
      # reuse_conn_total_time: 100
      # reuse_conn_max_request: 100
      # reuse_conn_max_count: 100
    ignore_errors: true
    register: server_pool_result

  - name: Debug Create Server Pool 
    ansible.builtin.debug:
      msg: "{{ server_pool_result }}"
      verbosity: 3

  - name: fail the play if the previous command did not succeed
    ansible.builtin.fail:
      msg: "{{ server_pool_result.res.results.message }}"
    when:
      - server_pool_result.failed == true
      - server_pool_result.res.results.message != 'A duplicate entry has already existed.'
