---
- name: Create Virtual Server Policy
  hosts: fortiweb
  gather_facts: false
  collections:
  - fortinet.fortiweb
  vars:
  # variables defined in fwebos_server_variables.yml

  tasks:
  - name: Create server policy
    fwebos_server_policy:
      action: add
      vdom: root
      retry_on_connect_failure: disable
      #protocol: HTTP
      client_certificate_forwarding: disable
      client_real_ip: disable
      urlcert_hlen: 32
      hsts_max_age: 15552000
      tls13_custom_cipher: TLS_AES_256_GCM_SHA384
      urlcert: disable
      syncookie: disable
      #service: HTTPS
      hsts_preload: disable
      sni_strict: disable
      client_certificate_forwarding_cert_header: X-Client-Cert
      retry_times_on_connect_failure: 3
      ssl_cipher: medium
      traffic_mirror_type: client-side
      multi_certificate: disable
      #multi_certificate: enable
      hsts_header: disable
      monitor_mode: disable
      deployment_mode: server-pool
      tls_v13: disable
      tls_v10: enable
      tls_v11: enable
      proxy_protocol: disable
      vserver: "{{ fwebos_virtual_server_name }}"
      real_ip_addr: 
      ssl_custom_cipher: ECDHE-ECDSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-GCM-SHA384 ECDHE-ECDSA-CHACHA20-POLY1305 ECDHE-RSA-CHACHA20-POLY1305 ECDHE-ECDSA-AES128-GCM-SHA256 ECDHE-RSA-AES128-GCM-SHA256 ECDHE-ECDSA-AES256-SHA384 ECDHE-RSA-AES256-SHA384 ECDHE-ECDSA-AES128-SHA256 ECDHE-RSA-AES128-SHA256 ECDHE-ECDSA-AES256-SHA ECDHE-RSA-AES256-SHA ECDHE-ECDSA-AES128-SHA ECDHE-RSA-AES128-SHA AES256-GCM-SHA384 AES128-GCM-SHA256 AES256-SHA256 AES128-SHA256
      retry_on_cache_size: 512
      http_to_https: disable
      hsts_include_subdomains: disable
      half_open_threshold: 8192
      retry_on_http_layer: disable
      traffic_mirror: disable
      client_certificate_forwarding_sub_header: X-Client-DN
      sni: disable
      ssl: enable
      web_cache: disable
      ssl_noreg: enable
      retry_on_http_response_codes: 404 408 500 501 502 503 504
      prefer_current_session: disable
      retry_times_on_http_layer: 3
      case_sensitive: disable
      name: "{{ fwebos_server_policy  }}"
      replacemsg: Predefined
      server_pool: "{{ fwebos_server_pool }}"
      retry_on: disable
      tls_v12: enable
      https_service: HTTPS
      http2: disable
      certificate_type: disable
      certificate: "{{ fwebos_certificate }}"
      http2_custom_cipher: ECDHE-ECDSA-AES256-GCM-SHA384 DHE-DSS-AES128-GCM-SHA256 DHE-RSA-AES128-GCM-SHA256 ECDHE-RSA-AES256-GCM-SHA384
      web_protection_profile: Inline Standard Protection
      #certificate_group: test
      #allow_hosts: test.com
      #intermediate_certificate_group: test
      tlog: disable
      chunk_encoding: enable
    ignore_errors: true
    register: server_policy_result

  - name: Debug Create Server Policy
    ansible.builtin.debug:
      msg: "{{ server_policy_result }}"
      verbosity: 3

  - name: fail the play if the previous command did not succeed
    ansible.builtin.fail:
      msg: "{{ server_policy_result.res.results.message }}"
    when:
      - server_policy_result.failed == true
      - server_policy_result.res.results.message != 'A duplicate entry has already existed.'
